# Generated by Django 3.2.9 on 2021-11-13 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuerySearch',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('search', models.TextField(unique=True, verbose_name=155)),
                ('amount', models.IntegerField(default=0)),
                ('firstSearch', models.IntegerField()),
                ('lastSearch', models.IntegerField()),
                ('numberResults', models.IntegerField()),
            ],
        ),
    ]
